# Generated by Django 5.2.7 on 2025-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_api', '0002_enhanced_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
