# Generated by Django 5.2.7 on 2025-10-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_api', '0004_complete_hiring_platform'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedjob',
            name='unique_saved_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], default='Full-time', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('candidate_email', 'job')},
        ),
    ]
